export const questionList = [
  { frontSide: "orange", backSide: "апельсин" },
  { frontSide: "banana", backSide: "банан" },
  { frontSide: "ham", backSide: "ветчина" },
  { frontSide: "Russian beet salad", backSide: "винегрет" },
  { frontSide: "grapes", backSide: "виноград" },
  { frontSide: "water", backSide: "вода" },
  { frontSide: "jam", backSide: "джем / варенье" },
  { frontSide: "caviar", backSide: "икра" },
  { frontSide: "cabbage", backSide: "капуста" },
  { frontSide: "sauerkraut", backSide: "квашеная капуста" },
{ frontSide: "cauliflower", backSide: "цветная капуста" },
{ frontSide: "potatoes", backSide: "картофель / картошка" },
  { frontSide: "Coke", backSide: "кока-кола" },
  { frontSide: "sausage", backSide: "колбаса" },
  { frontSide: "coffee", backSide: "кофе" },
  { frontSide: "chicken", backSide: "курица" },
  { frontSide: "lemonade", backSide: "лимонад" },
  { frontSide: "onion", backSide: "лук" },
  { frontSide: "butter / oil", backSide: "масло" },
  { frontSide: "vegetable oil", backSide: "растительное масло" },
  { frontSide: "milk", backSide: "молоко" },
  { frontSide: "carrots", backSide: "морковь" },
  { frontSide: "ice cream", backSide: "мороженое" },
  { frontSide: "meat", backSide: "мясо" },
  { frontSide: "vegetables", backSide: "овощи" },
  { frontSide: "cucumber", backSide: "огурец" },
  { frontSide: "pilaf", backSide: "плов" },
  { frontSide: "tomato", backSide: "помидор" },
  { frontSide: "produce / groceries", backSide: "продукты" },
  { frontSide: "bird / poultry", backSide: "птица" },
  { frontSide: "rice", backSide: "рис" },
  { frontSide: "fish", backSide: "рыба" },
  { frontSide: "salad", backSide: "салат" },
  { frontSide: "sour cream", backSide: "сметана" },
  { frontSide: "orange juice", backSide: "апельсиновый сок" },
  { frontSide: "cheese", backSide: "сыр" },
  { frontSide: "cake", backSide: "торт" },
  { frontSide: "fruit", backSide: "фрукты" },
  { frontSide: "bread", backSide: "хлеб" },
  { frontSide: "tea (green or black)", backSide: "чай" },
  { frontSide: "chocolate", backSide: "шоколад" },
  { frontSide: "apple", backSide: "яблоко" },
  { frontSide: "egg", backSide: "яйцо / яйца" },
  { frontSide: "supermarket", backSide: "супермаркет" },
  { frontSide: "market", backSide: "рынок" },
  { frontSide: "jar / can", backSide: "банка" },
  { frontSide: "bottle", backSide: "бутылка" },
{ frontSide: "loaf", backSide: "буханка" },
  { frontSide: "box", backSide: "коробка" },
  { frontSide: "piece", backSide: "кусок" },
  { frontSide: "money", backSide: "деньги" },
  { frontSide: "kopeck", backSide: "копейка" },
  { frontSide: "coffee maker", backSide: "кофеварка" },
{ frontSide: "credit card", backSide: "кредитная карточка" },
  { frontSide: "a drink", backSide: "напиток" },
  { frontSide: "rouble", backSide: "рубль" },
  { frontSide: "refrigerator", backSide: "холодильник" },
  { frontSide: "cent", backSide: "цент" },
  { frontSide: "person", backSide: "человек" },
  { frontSide: "cheap", backSide: "дешёвый" },
  { frontSide: "expensive", backSide: "дорогой" },
{ frontSide: "cheaper", backSide: "дешёвле" },
  { frontSide: "more expensive than", backSide: "дороже, чем" },
  { frontSide: "orange (adj.)", backSide: "апельсиновый" },
  { frontSide: "mineral water", backSide: "минеральная вода" },
{ frontSide: "dairy products", backSide: "молочные продукты" },
  { frontSide: "sweet", backSide: "сладкий" },
  { frontSide: "Swiss", backSide: "швейцарский" },
  { frontSide: "more / bigger", backSide: "больше" },
  { frontSide: "cheaply", backSide: "дёшево" },
  { frontSide: "expensively", backSide: "дорого" },
  { frontSide: "enough", backSide: "достаточно" },
  { frontSide: "little (of)", backSide: "мало" },
  { frontSide: "less / smaller", backSide: "меньше" },
  { frontSide: "a lot (of)", backSide: "много" },
{ frontSide: "probably", backSide: "наверное" },
  { frontSide: "must / need to", backSide: "надо" },
  { frontSide: "how much / how many", backSide: "сколько" },
{ frontSide: "too (much)", backSide: "слишком" },
  { frontSide: "then / in that case", backSide: "тогда" },
  { frontSide: "to take", backSide: "взять" },
  { frontSide: "to eat", backSide: "есть" },
  { frontSide: "to buy", backSide: "купить" },
  { frontSide: "to drink", backSide: "пить" },
  { frontSide: "to sell", backSide: "продавать" },
  { frontSide: "to cost", backSide: "стоить" },
  { frontSide: "to slice", backSide: "нарезать" },
  { frontSide: "to pay (with cash)", backSide: "платить (наличными)" },
  { frontSide: "just in case", backSide: "на всякий случай" },
  { frontSide: "teapot", backSide: "чайник" },
  { frontSide: "washing machine", backSide: "стиральная машина" },
  { frontSide: "vacuum cleaner", backSide: "пылесос" },
  { frontSide: "dishwasher", backSide: "посудомоечная машина" },
  { frontSide: "stove", backSide: "плита" },
  { frontSide: "microwave", backSide: "микроволновка" },
  { frontSide: "kiosk / stand", backSide: "ларёк" },
  { frontSide: "food store", backSide: "гастроном" },
  { frontSide: "How much does this cost?", backSide: "Сколько это стоит?" },
  { frontSide: "I don't have money / time", backSide: "у меня нет денег, времени" },
  { frontSide: "flatbread", backSide: "лаваш" }
];