export const allQuestionLists = [
    {
        'name': "Troika Unit 10",
        'words': [
            { frontSide: "science", backSide: "наука", listId: "Troika Unit 10" },
            { frontSide: "grade", backSide: "отметка", listId: "Troika Unit 10" },
            { frontSide: "grade A", backSide: "пятёрка", listId: "Troika Unit 10" },
            { frontSide: "grade C", backSide: "тройка", listId: "Troika Unit 10" },
            { frontSide: "grade B", backSide: "четвёрка", listId: "Troika Unit 10" },
            { frontSide: "class session", backSide: "занятие", listId: "Troika Unit 10" },
            { frontSide: "class", backSide: "класс", listId: "Troika Unit 10" },
            { frontSide: "graduate student", backSide: "аспирант", listId: "Troika Unit 10" },
            { frontSide: "classmate (university)", backSide: "однокурсник", listId: "Troika Unit 10" },
            { frontSide: "competition", backSide: "конкурс", listId: "Troika Unit 10" },
            { frontSide: "security guard", backSide: "охранник", listId: "Troika Unit 10" },
            { frontSide: "Korean", backSide: "корейский", listId: "Troika Unit 10" },
            { frontSide: "money", backSide: "деньги", listId: "Troika Unit 10" },
            { frontSide: "native", backSide: "родной", listId: "Troika Unit 10" },
            { frontSide: "first", backSide: "первый", listId: "Troika Unit 10" },
            { frontSide: "second", backSide: "второй", listId: "Troika Unit 10" },
            { frontSide: "third", backSide: "третий", listId: "Troika Unit 10" },
            { frontSide: "fourth", backSide: "четвёртый", listId: "Troika Unit 10" },
            { frontSide: "sixth", backSide: "шестой", listId: "Troika Unit 10" },
            { frontSide: "seventh", backSide: "седьмой", listId: "Troika Unit 10" },
            { frontSide: "eighth", backSide: "восьмой", listId: "Troika Unit 10" },
            { frontSide: "ninth", backSide: "девятый", listId: "Troika Unit 10" },
            { frontSide: "tenth", backSide: "десятый", listId: "Troika Unit 10" },
            { frontSide: "spring (adj.)", backSide: "весенний", listId: "Troika Unit 10" },
            { frontSide: "summer (adj.)", backSide: "летний", listId: "Troika Unit 10" },
            { frontSide: "fall (adj.)", backSide: "осенний", listId: "Troika Unit 10" },
            { frontSide: "entrance (adj.)", backSide: "вступительный", listId: "Troika Unit 10" },
            { frontSide: "to choose", backSide: "выбирать", listId: "Troika Unit 10" },
            { frontSide: "to give", backSide: "давать", listId: "Troika Unit 10" },
            { frontSide: "to happen / occur", backSide: "бывать", listId: "Troika Unit 10" },
            { frontSide: "to end / finish", backSide: "кончаться", listId: "Troika Unit 10" },
            { frontSide: "to answer", backSide: "отвечать", listId: "Troika Unit 10" },
            { frontSide: "to teach", backSide: "преподавать", listId: "Troika Unit 10" },
            { frontSide: "to continue", backSide: "продолжать", listId: "Troika Unit 10" },
            { frontSide: "to rent", backSide: "снимать", listId: "Troika Unit 10" },
            { frontSide: "to feel", backSide: "чувствовать", listId: "Troika Unit 10" },
            { frontSide: "good luck (to you)", backSide: "вам удачи", listId: "Troika Unit 10" },
            { frontSide: "personally", backSide: "лично", listId: "Troika Unit 10" },
            { frontSide: "with parents", backSide: "с родителями", listId: "Troika Unit 10" },
            { frontSide: "self", backSide: "сам / сама / сами", listId: "Troika Unit 10" },
            { frontSide: "much / a lot more", backSide: "намного", listId: "Troika Unit 10" },
            { frontSide: "to finish", backSide: "заканчивать", listId: "Troika Unit 10" },
            { frontSide: "subject", backSide: "предмет", listId: "Troika Unit 10" },
            { frontSide: "basis", backSide: "основе", listId: "Troika Unit 10" },
            { frontSide: "required", backSide: "обязательные", listId: "Troika Unit 10" },
            { frontSide: "school vacation", backSide: "каникулы", listId: "Troika Unit 10" },
            { frontSide: "essay", backSide: "сочинение", listId: "Troika Unit 10" },
            { frontSide: "good luck! (idiom)", backSide: "Ни пуха ни пера!", listId: "Troika Unit 10" },
            { frontSide: "I wish you good luck", backSide: "желаю вам удачи", listId: "Troika Unit 10" },
            { frontSide: "length", backSide: "длина", listId: "Troika Unit 10" },
            { frontSide: "orally", backSide: "устно", listId: "Troika Unit 10" },
            { frontSide: "independence", backSide: "самостоятельность", listId: "Troika Unit 10" },
            { frontSide: "negative", backSide: "отрицательный", listId: "Troika Unit 10" },
            { frontSide: "conditions", backSide: "условия", listId: "Troika Unit 10" },
            { frontSide: "cramped", backSide: "стеснённый", listId: "Troika Unit 10" },
            { frontSide: "quiet / quieter", backSide: "тихо / тише", listId: "Troika Unit 10" },
            { frontSide: "expensive / more expensive", backSide: "дорого / дороже", listId: "Troika Unit 10" },
            { frontSide: "noisy", backSide: "шумно", listId: "Troika Unit 10" },
            { frontSide: "cheap", backSide: "дешёво", listId: "Troika Unit 10" },
            { frontSide: "are held", backSide: "проводятся", listId: "Troika Unit 10" },
            { frontSide: "part", backSide: "часть", listId: "Troika Unit 10" },
            { frontSide: "little / few", backSide: "мало", listId: "Troika Unit 10" },
            { frontSide: "to study (at a place)", backSide: "учиться", listId: "Troika Unit 10" },
            { frontSide: "to study (a subject)", backSide: "изучать", listId: "Troika Unit 10" },
            { frontSide: "to read / write / speak Russian", backSide: "по-русски", listId: "Troika Unit 10" },
            { frontSide: "Russian (study / know / love)", backSide: "русски", listId: "Troika Unit 10" },
            { frontSide: "what language?", backSide: "какой язык", listId: "Troika Unit 10" },
            { frontSide: "quiz / test", backSide: "контрольная работа", listId: "Troika Unit 10" },
            { frontSide: "bachelor's degree", backSide: "бакалавр", listId: "Troika Unit 10" },
            { frontSide: "colleague", backSide: "коллега", listId: "Troika Unit 10" },
            { frontSide: "diploma", backSide: "диплом", listId: "Troika Unit 10" },
            { frontSide: "assignment", backSide: "задание", listId: "Troika Unit 10" },
            { frontSide: "foreign", backSide: "иностранный", listId: "Troika Unit 10" },
            { frontSide: "fifth", backSide: "пятый", listId: "Troika Unit 10" },
            { frontSide: "eleventh", backSide: "одиннадцатый", listId: "Troika Unit 10" },
            { frontSide: "winter (adj.)", backSide: "зимний", listId: "Troika Unit 10" },
            { frontSide: "future (adj.)", backSide: "будущий", listId: "Troika Unit 10" },
            { frontSide: "other / another", backSide: "другой", listId: "Troika Unit 10" },
            { frontSide: "to begin", backSide: "начинаться", listId: "Troika Unit 10" },
            { frontSide: "to receive", backSide: "получать", listId: "Troika Unit 10" },
            { frontSide: "except / besides", backSide: "кроме", listId: "Troika Unit 10" },
            { frontSide: "in another way / differently", backSide: "по-другому", listId: "Troika Unit 10" },
            { frontSide: "in the end / at the end", backSide: "в конце", listId: "Troika Unit 10" },
            { frontSide: "to last (imperfective)", backSide: "длиться", listId: "Troika Unit 10" },
            { frontSide: "to be occupied / engage in (NO direct object)", backSide: "заниматься", listId: "Troika Unit 10" },
            { frontSide: "whose (m / f / n / pl)", backSide: "чей / чья / чьё / чьи", listId: "Troika Unit 10" },
            { frontSide: "graduate school (program)", backSide: "аспирантура", listId: "Troika Unit 10" },
            { frontSide: "biology", backSide: "биология", listId: "Troika Unit 10" },
            { frontSide: "finance / finances", backSide: "финансы", listId: "Troika Unit 10" },
            { frontSide: "physics", backSide: "физика", listId: "Troika Unit 10" },
            { frontSide: "chemistry", backSide: "химия", listId: "Troika Unit 10" },
            { frontSide: "exam", backSide: "экзамен", listId: "Troika Unit 10" },
            { frontSide: "course", backSide: "курс", listId: "Troika Unit 10" },
            { frontSide: "seminar", backSide: "семинар", listId: "Troika Unit 10" },
            { frontSide: "lecture", backSide: "лекция", listId: "Troika Unit 10" },
            { frontSide: "specialty / major", backSide: "специальность", listId: "Troika Unit 10" },
            { frontSide: "why?", backSide: "почему", listId: "Troika Unit 10" },
            { frontSide: "difficult (adverb)", backSide: "трудно", listId: "Troika Unit 10" },
            { frontSide: "philological (related to languages, literature)", backSide: "филологический", listId: "Troika Unit 10" },
            { frontSide: "written (adj.)", backSide: "письменный", listId: "Troika Unit 10" },
            { frontSide: "difficult (adj.)", backSide: "трудный", listId: "Troika Unit 10" },
            { frontSide: "more difficult / harder", backSide: "труднее", listId: "Troika Unit 10" },
            { frontSide: "schoolboy / girl", backSide: "школьник / школьница", listId: "Troika Unit 10" },
            { frontSide: "semester", backSide: "семестр", listId: "Troika Unit 10" },
            { frontSide: "department", backSide: "факультет", listId: "Troika Unit 10" },
            { frontSide: "oral (adj)", backSide: "устный", listId: "Troika Unit 10" }
          ],
          'isCustom': false
    },
    {
        'name': "Troika Unit 11",
        "words": [
            { frontSide: "orange", backSide: "апельсин", listId: "Troika Unit 11" },
            { frontSide: "banana", backSide: "банан", listId: "Troika Unit 11" },
            { frontSide: "ham", backSide: "ветчина", listId: "Troika Unit 11" },
            { frontSide: "Russian beet salad", backSide: "винегрет", listId: "Troika Unit 11" },
            { frontSide: "grapes", backSide: "виноград", listId: "Troika Unit 11" },
            { frontSide: "water", backSide: "вода", listId: "Troika Unit 11" },
            { frontSide: "jam", backSide: "джем / варенье", listId: "Troika Unit 11" },
            { frontSide: "caviar", backSide: "икра", listId: "Troika Unit 11" },
            { frontSide: "cabbage", backSide: "капуста", listId: "Troika Unit 11" },
            { frontSide: "sauerkraut", backSide: "квашеная капуста", listId: "Troika Unit 11" },
            { frontSide: "cauliflower", backSide: "цветная капуста", listId: "Troika Unit 11" },
            { frontSide: "potatoes", backSide: "картофель / картошка", listId: "Troika Unit 11" },
            { frontSide: "Coke", backSide: "кока-кола", listId: "Troika Unit 11" },
            { frontSide: "sausage", backSide: "колбаса", listId: "Troika Unit 11" },
            { frontSide: "coffee", backSide: "кофе", listId: "Troika Unit 11" },
            { frontSide: "chicken", backSide: "курица", listId: "Troika Unit 11" },
            { frontSide: "lemonade", backSide: "лимонад", listId: "Troika Unit 11" },
            { frontSide: "onion", backSide: "лук", listId: "Troika Unit 11" },
            { frontSide: "butter / oil", backSide: "масло", listId: "Troika Unit 11" },
            { frontSide: "vegetable oil", backSide: "растительное масло", listId: "Troika Unit 11" },
            { frontSide: "milk", backSide: "молоко", listId: "Troika Unit 11" },
            { frontSide: "carrots", backSide: "морковь", listId: "Troika Unit 11" },
            { frontSide: "ice cream", backSide: "мороженое", listId: "Troika Unit 11" },
            { frontSide: "meat", backSide: "мясо", listId: "Troika Unit 11" },
            { frontSide: "vegetables", backSide: "овощи", listId: "Troika Unit 11" },
            { frontSide: "cucumber", backSide: "огурец", listId: "Troika Unit 11" },
            { frontSide: "pilaf", backSide: "плов", listId: "Troika Unit 11" },
            { frontSide: "tomato", backSide: "помидор", listId: "Troika Unit 11" },
            { frontSide: "produce / groceries", backSide: "продукты", listId: "Troika Unit 11" },
            { frontSide: "bird / poultry", backSide: "птица", listId: "Troika Unit 11" },
            { frontSide: "rice", backSide: "рис", listId: "Troika Unit 11" },
            { frontSide: "fish", backSide: "рыба", listId: "Troika Unit 11" },
            { frontSide: "salad", backSide: "салат", listId: "Troika Unit 11" },
            { frontSide: "sour cream", backSide: "сметана", listId: "Troika Unit 11" },
            { frontSide: "orange juice", backSide: "апельсиновый сок", listId: "Troika Unit 11" },
            { frontSide: "cheese", backSide: "сыр", listId: "Troika Unit 11" },
            { frontSide: "cake", backSide: "торт", listId: "Troika Unit 11" },
            { frontSide: "fruit", backSide: "фрукты", listId: "Troika Unit 11" },
            { frontSide: "bread", backSide: "хлеб", listId: "Troika Unit 11" },
            { frontSide: "tea (green or black)", backSide: "чай", listId: "Troika Unit 11" },
            { frontSide: "chocolate", backSide: "шоколад", listId: "Troika Unit 11" },
            { frontSide: "apple", backSide: "яблоко", listId: "Troika Unit 11" },
            { frontSide: "egg", backSide: "яйцо / яйца", listId: "Troika Unit 11" },
            { frontSide: "supermarket", backSide: "супермаркет", listId: "Troika Unit 11" },
            { frontSide: "market", backSide: "рынок", listId: "Troika Unit 11" },
            { frontSide: "jar / can", backSide: "банка", listId: "Troika Unit 11" },
            { frontSide: "bottle", backSide: "бутылка", listId: "Troika Unit 11" },
            { frontSide: "loaf", backSide: "буханка", listId: "Troika Unit 11" },
            { frontSide: "box", backSide: "коробка", listId: "Troika Unit 11" },
            { frontSide: "piece", backSide: "кусок", listId: "Troika Unit 11" },
            { frontSide: "money", backSide: "деньги", listId: "Troika Unit 11" },
            { frontSide: "kopeck", backSide: "копейка", listId: "Troika Unit 11" },
            { frontSide: "coffee maker", backSide: "кофеварка", listId: "Troika Unit 11" },
            { frontSide: "credit card", backSide: "кредитная карточка", listId: "Troika Unit 11" },
            { frontSide: "a drink", backSide: "напиток", listId: "Troika Unit 11" },
            { frontSide: "rouble", backSide: "рубль", listId: "Troika Unit 11" },
            { frontSide: "refrigerator", backSide: "холодильник", listId: "Troika Unit 11" },
            { frontSide: "cent", backSide: "цент", listId: "Troika Unit 11" },
            { frontSide: "person", backSide: "человек", listId: "Troika Unit 11" },
            { frontSide: "cheap", backSide: "дешёвый", listId: "Troika Unit 11" },
            { frontSide: "expensive", backSide: "дорогой", listId: "Troika Unit 11" },
            { frontSide: "cheaper", backSide: "дешёвле", listId: "Troika Unit 11" },
            { frontSide: "more expensive than", backSide: "дороже, чем", listId: "Troika Unit 11" },
            { frontSide: "orange (adj.)", backSide: "апельсиновый", listId: "Troika Unit 11" },
            { frontSide: "mineral water", backSide: "минеральная вода", listId: "Troika Unit 11" },
            { frontSide: "dairy products", backSide: "молочные продукты", listId: "Troika Unit 11" },
            { frontSide: "sweet", backSide: "сладкий", listId: "Troika Unit 11" },
            { frontSide: "Swiss", backSide: "швейцарский", listId: "Troika Unit 11" },
            { frontSide: "more / bigger", backSide: "больше", listId: "Troika Unit 11" },
            { frontSide: "cheaply", backSide: "дёшево", listId: "Troika Unit 11" },
            { frontSide: "expensively", backSide: "дорого", listId: "Troika Unit 11" },
            { frontSide: "enough", backSide: "достаточно", listId: "Troika Unit 11" },
            { frontSide: "little (of)", backSide: "мало", listId: "Troika Unit 11" },
            { frontSide: "less / smaller", backSide: "меньше", listId: "Troika Unit 11" },
            { frontSide: "a lot (of)", backSide: "много", listId: "Troika Unit 11" },
            { frontSide: "probably", backSide: "наверное", listId: "Troika Unit 11" },
            { frontSide: "must / need to", backSide: "надо", listId: "Troika Unit 11" },
            { frontSide: "how much / how many", backSide: "сколько", listId: "Troika Unit 11" },
            { frontSide: "too (much)", backSide: "слишком", listId: "Troika Unit 11" },
            { frontSide: "then / in that case", backSide: "тогда", listId: "Troika Unit 11" },
            { frontSide: "to take", backSide: "взять", listId: "Troika Unit 11" },
            { frontSide: "to eat", backSide: "есть", listId: "Troika Unit 11" },
            { frontSide: "to buy", backSide: "купить", listId: "Troika Unit 11" },
            { frontSide: "to drink", backSide: "пить", listId: "Troika Unit 11" },
            { frontSide: "to sell", backSide: "продавать", listId: "Troika Unit 11" },
            { frontSide: "to cost", backSide: "стоить", listId: "Troika Unit 11" },
            { frontSide: "to slice", backSide: "нарезать", listId: "Troika Unit 11" },
            { frontSide: "to pay (with cash)", backSide: "платить (наличными)", listId: "Troika Unit 11" },
            { frontSide: "just in case", backSide: "на всякий случай", listId: "Troika Unit 11" },
            { frontSide: "teapot", backSide: "чайник", listId: "Troika Unit 11" },
            { frontSide: "washing machine", backSide: "стиральная машина", listId: "Troika Unit 11" },
            { frontSide: "vacuum cleaner", backSide: "пылесос", listId: "Troika Unit 11" },
            { frontSide: "dishwasher", backSide: "посудомоечная машина", listId: "Troika Unit 11" },
            { frontSide: "stove", backSide: "плита", listId: "Troika Unit 11" },
            { frontSide: "microwave", backSide: "микроволновка", listId: "Troika Unit 11" },
            { frontSide: "kiosk / stand", backSide: "ларёк", listId: "Troika Unit 11" },
            { frontSide: "food store", backSide: "гастроном", listId: "Troika Unit 11" },
            { frontSide: "How much does this cost?", backSide: "Сколько это стоит?", listId: "Troika Unit 11" },
            { frontSide: "I don't have money / time", backSide: "у меня нет денег, времени", listId: "Troika Unit 11" },
            { frontSide: "flatbread", backSide: "лаваш", listId: "Troika Unit 11" }
          ],
          'isCustom': false
    }, {
        'name': 'Troika Unit 12',
        'words': [
            { frontSide: "ticket", backSide: "билет", listId: "Troika Unit 12" },
            { frontSide: "action film", backSide: "боевик", listId: "Troika Unit 12" },
            { frontSide: "alarm clock", backSide: "будильник", listId: "Troika Unit 12" },
            { frontSide: "entrance", backSide: "вход", listId: "Troika Unit 12" },
            { frontSide: "exhibit", backSide: "выставка", listId: "Troika Unit 12" },
            { frontSide: "channel", backSide: "канал", listId: "Troika Unit 12" },
            { frontSide: "box office", backSide: "касса", listId: "Troika Unit 12" },
            { frontSide: "skating rink", backSide: "каток", listId: "Troika Unit 12" },
            { frontSide: "club", backSide: "клуб", listId: "Troika Unit 12" },
            { frontSide: "concert", backSide: "концерт", listId: "Troika Unit 12" },
            { frontSide: "match", backSide: "матч", listId: "Troika Unit 12" },
            { frontSide: "minute", backSide: "минута", listId: "Troika Unit 12" },
            { frontSide: "broadcast", backSide: "передача", listId: "Troika Unit 12" },
            { frontSide: "song", backSide: "песня", listId: "Troika Unit 12" },
            { frontSide: "half an hour", backSide: "полчаса", listId: "Troika Unit 12" },
            { frontSide: "briefcase", backSide: "портфель", listId: "Troika Unit 12" },
            { frontSide: "invitation", backSide: "приглашение", listId: "Troika Unit 12" },
            { frontSide: "program", backSide: "программа", listId: "Troika Unit 12" },
            { frontSide: "report", backSide: "реферат", listId: "Troika Unit 12" },
            { frontSide: "show", backSide: "сеанс", listId: "Troika Unit 12" },
            { frontSide: "list", backSide: "список", listId: "Troika Unit 12" },
            { frontSide: "bag", backSide: "сумка", listId: "Troika Unit 12" },
          
            { frontSide: "main (adj.)", backSide: "главный", listId: "Troika Unit 12" },
            { frontSide: "home (adj.)", backSide: "домашний", listId: "Troika Unit 12" },
            { frontSide: "extra (adj.)", backSide: "лишний", listId: "Troika Unit 12" },
            { frontSide: "theater (adj.)", backSide: "театральный", listId: "Troika Unit 12" },
          
            { frontSide: "for a long time", backSide: "долго", listId: "Troika Unit 12" },
            { frontSide: "still", backSide: "ещё", listId: "Troika Unit 12" },
            { frontSide: "not yet", backSide: "ещё не", listId: "Troika Unit 12" },
            { frontSide: "no way", backSide: "никак", listId: "Troika Unit 12" },
            { frontSide: "quietly", backSide: "тихо", listId: "Troika Unit 12" },
            { frontSide: "in that case", backSide: "тогда", listId: "Troika Unit 12" },
            { frontSide: "exactly", backSide: "точно", listId: "Troika Unit 12" },
            { frontSide: "already", backSide: "уже", listId: "Troika Unit 12" },
            { frontSide: "all", backSide: "весь", listId: "Troika Unit 12" },
            { frontSide: "all day", backSide: "весь день", listId: "Troika Unit 12" },
            { frontSide: "something", backSide: "что-нибудь", listId: "Troika Unit 12" },
          
            { frontSide: "in (time period)", backSide: "за", listId: "Troika Unit 12" },
            { frontSide: "after", backSide: "после", listId: "Troika Unit 12" },
            { frontSide: "by / at", backSide: "у", listId: "Troika Unit 12" },
          
            { frontSide: "to take", backSide: "брать / взять", listId: "Troika Unit 12" },
            { frontSide: "to see", backSide: "видеть / увидеть", listId: "Troika Unit 12" },
            { frontSide: "to meet", backSide: "встречаться / встретиться", listId: "Troika Unit 12" },
            { frontSide: "to prepare", backSide: "готовить / приготовить", listId: "Troika Unit 12" },
            { frontSide: "to prepare (for exam)", backSide: "готовиться / подготовиться", listId: "Troika Unit 12" },
            { frontSide: "to give", backSide: "давать / дать", listId: "Troika Unit 12" },
            { frontSide: "to do", backSide: "делать / сделать", listId: "Troika Unit 12" },
            { frontSide: "to go (vehicle)", backSide: "ехать / поехать", listId: "Troika Unit 12" },
            { frontSide: "to eat breakfast", backSide: "завтракать / позавтракать", listId: "Troika Unit 12" },
            { frontSide: "to end", backSide: "заканчиваться / закончиться", listId: "Troika Unit 12" },
            { frontSide: "to call", backSide: "звонить / позвонить", listId: "Troika Unit 12" },
            { frontSide: "to put", backSide: "класть / положить", listId: "Troika Unit 12" },
            { frontSide: "to buy", backSide: "покупать / купить", listId: "Troika Unit 12" },
            { frontSide: "to be able", backSide: "мочь / смочь", listId: "Troika Unit 12" },
            { frontSide: "to wash", backSide: "мыть / вымыть", listId: "Troika Unit 12" },
            { frontSide: "to begin", backSide: "начинать / начать", listId: "Troika Unit 12" },
            { frontSide: "to begin (itself)", backSide: "начинаться / начаться", listId: "Troika Unit 12" },
            { frontSide: "to eat lunch", backSide: "обедать / пообедать", listId: "Troika Unit 12" },
            { frontSide: "to be late", backSide: "опаздывать / опоздать", listId: "Troika Unit 12" },
            { frontSide: "to answer", backSide: "отвечать / ответить", listId: "Troika Unit 12" },
            { frontSide: "to relax", backSide: "отдыхать / отдохнуть", listId: "Troika Unit 12" },
            { frontSide: "to open", backSide: "открывать / открыть", listId: "Troika Unit 12" },
            { frontSide: "to pass / convey", backSide: "передавать / передать", listId: "Troika Unit 12" },
            { frontSide: "to sing", backSide: "петь / спеть", listId: "Troika Unit 12" },
            { frontSide: "to write", backSide: "писать / написать", listId: "Troika Unit 12" },
            { frontSide: "to drink", backSide: "пить / выпить", listId: "Troika Unit 12" },
            { frontSide: "to leave (by vehicle)", backSide: "ехать / поехать", listId: "Troika Unit 12" },
            { frontSide: "to go (by foot)", backSide: "идти / пойти", listId: "Troika Unit 12" },
            { frontSide: "to show", backSide: "показывать / показать", listId: "Troika Unit 12" },
            { frontSide: "to place", backSide: "класть / положить", listId: "Troika Unit 12" },
            { frontSide: "to receive", backSide: "получать / получить", listId: "Troika Unit 12" },
            { frontSide: "to invite", backSide: "приглашать / пригласить", listId: "Troika Unit 12" },
            { frontSide: "to arrive", backSide: "приходить / прийти", listId: "Troika Unit 12" },
            { frontSide: "to accept", backSide: "принимать / принять", listId: "Troika Unit 12" },
            { frontSide: "to wake up", backSide: "просыпаться / проснуться", listId: "Troika Unit 12" },
            { frontSide: "to pass an exam", backSide: "сдавать / сдать", listId: "Troika Unit 12" },
            { frontSide: "to watch", backSide: "смотреть / посмотреть", listId: "Troika Unit 12" },
            { frontSide: "to do laundry", backSide: "стирать / выстирать", listId: "Troika Unit 12" },
            { frontSide: "to dance", backSide: "танцевать", listId: "Troika Unit 12" },
            { frontSide: "to clean", backSide: "убирать / убрать", listId: "Troika Unit 12" },
            { frontSide: "to eat dinner", backSide: "ужинать / поужинать", listId: "Troika Unit 12" },
            { frontSide: "to find out", backSide: "узнавать / узнать", listId: "Troika Unit 12" },
            { frontSide: "to smile", backSide: "улыбаться / улыбнуться", listId: "Troika Unit 12" },
            { frontSide: "to want", backSide: "хотеть", listId: "Troika Unit 12" },
            { frontSide: "to read", backSide: "читать / прочитать", listId: "Troika Unit 12" },
            
            { frontSide: "all the best", backSide: "Всего хорошего", listId: "Troika Unit 12" },
            { frontSide: "let's watch", backSide: "давай посмотрим", listId: "Troika Unit 12" },
            { frontSide: "agreed", backSide: "договорились", listId: "Troika Unit 12" },
            { frontSide: "out of town", backSide: "за город", listId: "Troika Unit 12" },
            { frontSide: "unfortunately", backSide: "к сожалению", listId: "Troika Unit 12" },
            { frontSide: "all right", backSide: "ладно", listId: "Troika Unit 12" },
            { frontSide: "just a minute", backSide: "минуточку", listId: "Troika Unit 12" },
            { frontSide: "have to", backSide: "надо", listId: "Troika Unit 12" },
            { frontSide: "well done", backSide: "молодец", listId: "Troika Unit 12" },
            { frontSide: "you're welcome", backSide: "не за что", listId: "Troika Unit 12" },
            { frontSide: "sold out", backSide: "продан", listId: "Troika Unit 12" },
            { frontSide: "with pleasure", backSide: "с удовольствием", listId: "Troika Unit 12" },
            { frontSide: "with me", backSide: "со мной", listId: "Troika Unit 12" },
            { frontSide: "I am tired", backSide: "я устал", listId: "Troika Unit 12" }
          ],
        'isCustom': false
    }
  ]